# Generated by Django 5.2 on 2025-05-31 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarter',
            name='float_precision',
            field=models.PositiveIntegerField(default=9),
        ),
    ]
