# Generated by Django 5.2 on 2025-06-07 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_quarter_float_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='float_precision',
            field=models.PositiveIntegerField(default=9, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
