# Generated by Django 5.2 on 2025-06-11 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_quarter_float_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='quarter_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='pages.excelfile'),
        ),
    ]
