services:
  django:
    build: .
    container_name: django
    command: gunicorn dashboard.wsgi:application --chdir dashboard --bind 0.0.0.0:8000
    volumes:
      - ./dashboard:/app  # map the django app into the container's /app
      - ./staticfiles:/static  # expose collected static files to Nginx
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./dashboard/staticfiles:/static
      - ./docker/nginx:/etc/nginx/conf.d:ro
    depends_on:
      - django
    networks:
      - webnet
    extra_hosts:
      - "dashboard-app.local:127.0.0.1"
      - "127.0.0.1:127.0.0.1"

networks:
  webnet:
