version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
    - 8000
    env_file:
      - ./infra/.env.prod
    depends_on:
      - postgres
      - mongo
  
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./infra/.env.prod
  
  mongo:
    image: mongo:6
    env_file:
    - ./infra/.env.prod
    restart: always
    volumes:
      - mongo_data:/data/db
    expose:
      - 27017
  nginx:
    build: ./infra/nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
volumes:
  postgres_data:
  mongo_data:
  static_volume:
