version: '3.8'

services:
  web:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
    - 8000
    env_file:
      - ./infra/.env.prod
    depends_on:
      - postgres
        
  postgres:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./infra/.env.prod
  nginx:
    build: ./infra/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles
      - ./infra/nginx/certs:/etc/nginx/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`dashboard-app.local`)"
      - "traefik.http.routers.whoami.entrypoints=web"
volumes:
  postgres_data:
  mongo_data:
  static_volume:
