services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./staticfiles:/static
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/static
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  static_volume:
