services:
  web:
    build: ./backend
    command: sh ./scripts/entrypoint.sh
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./infra/.env.dev
    depends_on:
      - postgres
      - mongo

  postgres:
    env_file:
      - ./infra/.env.dev
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mongo:
    image: mongo:6
    env_file:
    - ./infra/.env.dev
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

volumes:
  postgres_data:
  mongo_data: