version: '3.8'

services:
  web:
    build: ./backend
    command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
      - static_volume:/home/app/web/staticfiles
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
  nginx:
    build: ./infra/nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/staticfiles