name: Deploy to VPS & Purge Cloudflare Cache

on:
  push:
    branches:
      - master
    paths:
      - 'backend/**'      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "Checking for updates..."
            cd isel_final_project
            git fetch origin master
            LOCAL=$(git rev-parse @)
            REMOTE=$(git rev-parse @{u})
            BASE=$(git merge-base @ @{u})

            if [ "$LOCAL" = "$REMOTE" ]; then
              echo "No updates. Skipping deploy."
              exit 0
            elif [ "$LOCAL" = "$BASE" ]; then
              echo "New commits found. Deploying..."
              sh infra/deploy.sh
            else
              echo "Branch is ahead or diverged. Manual review needed."
              exit 1
            fi

      - name: Purge Cloudflare Cache
        if: success()  # only runs if deploy succeeded
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/purge_cache" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data '{"purge_everything":true}'
