name: Build LaTeX Report

on:
  push:
    branches:
      - "*"
    paths:
      - 'docs/final_report/**'
      - '.github/workflows/latex-workflows.yml'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build-report:
    runs-on: ubuntu-latest

    steps:
      - name: Pull and save Docker image if not cached
        if: steps.cache-docker-image.outputs.cache-hit != 'true'
        run: |
          docker pull alicescfernandes/compiler_image:latest

      - name: Run LaTeX build script
        run: |
          docker run --rm -v "${{ github.workspace }}/docs/final_report:/data" alicescfernandes/compiler_image:latest ls -la
          docker run --rm -v "${{ github.workspace }}/docs/final_report:/data" alicescfernandes/compiler_image:latest

      - name: Upload compiled PDF
        uses: actions/upload-artifact@v4
        with:
          name: final-report
          path: docs/final_report/build/final_report.pdf
